"""Round 2 (academic-paper revision, re-review residuals on the Round-1 roadmap)."""
exec(open(__import__('os').path.dirname(__import__('os').path.abspath(__file__)) + '/edit_common.py').read())
E('To separate multiscale dynamics', 'Podobnik et al. (2011) established the analytical finite-sample distribution for hypothesis testing', 'Podobnik et al. (2011) proposed statistical tests for power-law cross-correlations', 'RR14 domain W6')
E('In nested equity index systems', 'Across Southeast Asian equity markets, index providers routinely employ', 'Across the equity markets of the Association of Southeast Asian Nations (ASEAN), index providers use', 'Abbrev ASEAN in body')
E('In nested equity index systems', 'While mature ASEAN exchanges, such as Bursa Malaysia, support continuous cash-futures arbitrage and market completeness through Regulated Short Selling (RSS) and Intraday Short Selling (IDSS) on eligible constituent equities, emerging frontier exchanges frequently operate under binding short-sale prohibitions and slower settlement cycles.', 'Bursa Malaysia permits Regulated Short Selling (RSS) and Intraday Short Selling (IDSS) on eligible constituents, whereas Vietnam prohibits cash short selling (Section 1.1).', 'RR7/RR16 unsupported regional generalization')
E('The primary microstructure constraint', 'heavily sold equities frequently hit lower limits, causing liquidity to freeze', 'heavily sold stocks can reach the lower limit, where trading dries up', 'RR15 price-band wording')
E('Finally, securities legislation', 'no exchange-traded hedging instrument exists for the mid-cap segment', 'no futures contract is listed on a mid-cap index', 'RR15 derivative claim')
E('We also account for the Epps', 'aggregation synchronizes price discovery, producing a positive scaling slope that reflects the fading of microstructure frictions combined with gradual information diffusion (Hong and Stein 1999).', 'aggregation synchronizes price discovery and can produce a positive scaling slope; gradual information diffusion (Hong and Stein 1999) can have the same effect. Section 3.7 tests whether such slopes are present.', 'RR1 methods pre-judged result')
DROP('Economic Mechanisms and Identification Boundaries', 'pseudo-heading inconsistent with heading hierarchy')
E('In the turbulent regime, the static model', 'the variance of the underlying assets has risen', 'the variance of VN30 returns has risen', 'accuracy: delta refers to VN30')
E('Table 7 shows that a higher large-cap weight', 'remains at least 0.052 below', 'remains at least 0.05 below', 'traceability: 0.977-0.924=0.053 from rounded table')
E('The second tier is the Extended Historical', ' All four frequencies overlap without any calendar gap in the first tier, which is used for cross-frequency comparisons.', '', 'redundant with first-tier paragraph')
E('To remove deterministic intraday patterns', 'using ordinary least squares (', 'using ordinary least squares (OLS; ', 'Abbrev OLS introduced')
E('Because the number of segments shrinks', 'with GARCH(1,1) surrogates', 'with generalized autoregressive conditional heteroskedasticity, GARCH(1,1), surrogates', 'Abbrev GARCH introduced')
E('Abstract:', 'Utilizing Detrended', 'Using Detrended', 'style')
E('Abstract:', 'this study illustrates that', 'this study shows that', 'style')
E('Secondly, we provide', 'Mid-cap diversification failure during Vietnamese market stress is therefore', 'The loss of mid-cap diversification during Vietnamese market stress is therefore', 'RR6 overclaim')
save(S + '/round2_edits.md')
